services:
  - type: web
    name: heap-project
    runtime: python
    plan: free
    buildCommand: pip install -r requirements-gerby.txt && make gerby-deploy-build
    startCommand: cd gerby-website && gunicorn wsgi:application --bind 0.0.0.0:$PORT
